FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .


RUN go build -o user-service ./cmd/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/admin-service .
COPY .env . 

EXPOSE 50053

CMD ["./user-service"]