name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, admin, user, test-section, test-generate, queue-job, filter, geteway]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Docker Image
        run: |
          cd ${{ matrix.service }}
          docker build -t gopherkhb/${{ matrix.service }}:latest .
          docker push gopherkhb/${{ matrix.service }}:latest
