name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.24]
        service: [auth, admin, user, test-section, test-generate, queue-job, filter, geteway]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Build ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          go build -o bin/${{ matrix.service }} ./cmd/main.go

      - name: Test ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          go test ./...
